### ISSUE TITLE
Animated armoury compatibility is broken at default settings (reach inconsistencies)

### ISSUE THREAD

**Issue by helariII** [Synthesis-Collective/speedandreachfixes#2]
In [Program.cs](https://github.com/Synthesis-Collective/speedandreachfixes/blob/master/SpeedandReachFixes/Program.cs) in the function AdjustWeaponReach under the section commented as animated armory support animated armoury weapons are assigned a modifier to their weapon reach based on their keywords. The modifiers are substracted from reach values set earlier for vanilla weapon types (also based on keywords).

The problem is that the modifiers are substracted even when it doesn't make sense (like for pikes and halberds) and they sometimes result in very low reach (especially for claws) by default.

For example, a pike weapon from animated armoury has a base reach of 1.7, a vanilla greatsword has a reach of 1.3.

Running the speed and reach fixes patcher with default settings results in a reach of 0.88 for the greatsword and a reach of 0.68 for the pike (0.88 - 0.20) when a pike should clearly be longer than a greatsword.

Weapons like claws at default settings can end up with such a low reach that NPCs don't know how to use them anymore.

Suggestion:

Allow setting individual lengths for animated armory weapons by changing for example:

`else if (weapon.HasKeyword(NewArmoury.Keyword.WeapTypePike))       weapon.Data.Reach = weapon.Data.Reach - Settings.Pike.Reach;`

to:

`else if (weapon.HasKeyword(NewArmoury.Keyword.WeapTypePike))       weapon.Data.Reach =  Settings.Pike.Reach;`

for each weapon type.

Default reach values for the new weapons can be calculated by the ratio of the vanilla weapon reach and the corresponding animated armoury weapon reach of the same type. For example a workable default reach for an animated armoury pike is:
(1.7/1.3)*0.88 = 1.15...

Alternatively the defaults can be set by testing ingame and tweaking the weapons' reach based on how they look.

Alternatively make the current modifiers more sane (add reach instead of reduce) and explain them in the settings menu so the user understands how they work (it's easy to mistake them for the absolute reach of the weapon type).

Weapons having multiple type keywords is intended. For example from the animated armoury for legendary edition changelog: "Gave all the Pikes The Greatsword keyword so they beneifit from Greatsword perks".

Weapons must have vanilla weapon type keywords to benefit from vanilla weapon perks or perks from mods like vokrii or ordinator. Weapons without applicable type perks are underpowered. I think the new keywords (pike, halberd, claw, etc.) are simply there to allow the weapons to animate correctly via DAR.

**Comment by Noggog** [comment]
@radj307 has an experimental branch with settings that are a lot more flexible:
https://github.com/radj307/speedandreachfixes

Give it a spin and see if it helps with the issues you've outlined

**Comment by Noggog** [comment]
Going to close, as I believe the new 2.0 changes radj put in should address most of these concerns?   If not, definitely let us know and reopen
