### ISSUE TITLE
Malformed formKey string

### ISSUE THREAD

**Issue by FailPail** [Synthesis-Collective/speedandreachfixes#8]
Started Getting this when I tried it. I wouldn't know where to start, but I know its not working.

[error.txt](https://github.com/Synthesis-Collective/speedandreachfixes/files/7470193/error.txt)

**Comment by FailPail** [comment]
User Error

**Comment by Noggog** [comment]
Synth's code has been improved to handle this a bit better, too, but hasn't been released with the new code included yet.

Should just be seen as a null FormKey (all zeros) rather than dying
