### ISSUE TITLE
VR Supported?

### ISSUE THREAD

**Issue by BrentW89** [Synthesis-Collective/speedandreachfixes#9]
Does this improve things in VR?  Many times I get hit when the weapon doesn't look like it would have reached.

**Comment by radj307** [comment]
The default settings were ported from the original Speed and Reach Fixes zEdit patcher and may not be adequate for VR, but these are configurable through the Synthesis GUI.

I am unable to test things in VR as I don't have a headset; if you find a configuration that works better with VR please post it here, improving on the default configuration would be great!

**Comment by BrentW89** [comment]
I don’t know if it’s perfect, but it certainly improves things. Before, enemies had an insane reach and now it seems more reasonable. Thank you for the mod!
